/**
 * Static sector and industry mapping for known stocks.
 * Used as a reliable fallback when Yahoo Finance API does not return sector/industry data.
 * This data is stable and rarely changes for established companies.
 */

interface SectorInfo {
  sector: string;
  industry: string;
}

export const STOCK_SECTORS: Record<string, SectorInfo> = {
  // ===== TECHNOLOGY =====
  'AAPL': { sector: 'Technology', industry: 'Consumer Electronics' },
  'MSFT': { sector: 'Technology', industry: 'Software - Infrastructure' },
  'GOOGL': { sector: 'Communication Services', industry: 'Internet Content & Information' },
  'GOOG': { sector: 'Communication Services', industry: 'Internet Content & Information' },
  'AMZN': { sector: 'Consumer Cyclical', industry: 'Internet Retail' },
  'NVDA': { sector: 'Technology', industry: 'Semiconductors' },
  'META': { sector: 'Communication Services', industry: 'Internet Content & Information' },
  'TSLA': { sector: 'Consumer Cyclical', industry: 'Auto Manufacturers' },
  'AVGO': { sector: 'Technology', industry: 'Semiconductors' },
  'ORCL': { sector: 'Technology', industry: 'Software - Infrastructure' },
  'ADBE': { sector: 'Technology', industry: 'Software - Infrastructure' },
  'CRM': { sector: 'Technology', industry: 'Software - Application' },
  'AMD': { sector: 'Technology', industry: 'Semiconductors' },
  'INTC': { sector: 'Technology', industry: 'Semiconductors' },
  'NFLX': { sector: 'Communication Services', industry: 'Entertainment' },
  'QCOM': { sector: 'Technology', industry: 'Semiconductors' },
  'TXN': { sector: 'Technology', industry: 'Semiconductors' },
  'CSCO': { sector: 'Technology', industry: 'Communication Equipment' },
  'ACN': { sector: 'Technology', industry: 'Information Technology Services' },
  'IBM': { sector: 'Technology', industry: 'Information Technology Services' },
  'NOW': { sector: 'Technology', industry: 'Software - Application' },
  'INTU': { sector: 'Technology', industry: 'Software - Application' },
  'AMAT': { sector: 'Technology', industry: 'Semiconductor Equipment & Materials' },
  'ADI': { sector: 'Technology', industry: 'Semiconductors' },
  'LRCX': { sector: 'Technology', industry: 'Semiconductor Equipment & Materials' },
  'MU': { sector: 'Technology', industry: 'Semiconductors' },
  'KLAC': { sector: 'Technology', industry: 'Semiconductor Equipment & Materials' },
  'SNPS': { sector: 'Technology', industry: 'Software - Infrastructure' },
  'CDNS': { sector: 'Technology', industry: 'Software - Application' },
  'MRVL': { sector: 'Technology', industry: 'Semiconductors' },
  'PANW': { sector: 'Technology', industry: 'Software - Infrastructure' },
  'CRWD': { sector: 'Technology', industry: 'Software - Infrastructure' },
  'FTNT': { sector: 'Technology', industry: 'Software - Infrastructure' },
  'WDAY': { sector: 'Technology', industry: 'Software - Application' },
  'TEAM': { sector: 'Technology', industry: 'Software - Application' },
  'DDOG': { sector: 'Technology', industry: 'Software - Application' },
  'ZS': { sector: 'Technology', industry: 'Software - Infrastructure' },
  'SNOW': { sector: 'Technology', industry: 'Software - Application' },
  'NET': { sector: 'Technology', industry: 'Software - Infrastructure' },
  'PLTR': { sector: 'Technology', industry: 'Software - Infrastructure' },
  'UBER': { sector: 'Technology', industry: 'Software - Application' },
  'ABNB': { sector: 'Consumer Cyclical', industry: 'Travel Services' },
  'SQ': { sector: 'Technology', industry: 'Software - Infrastructure' },
  'SHOP': { sector: 'Technology', industry: 'Software - Application' },
  'MELI': { sector: 'Consumer Cyclical', industry: 'Internet Retail' },
  'SE': { sector: 'Communication Services', industry: 'Internet Content & Information' },
  'COIN': { sector: 'Financial Services', industry: 'Financial Data & Stock Exchanges' },
  'HOOD': { sector: 'Financial Services', industry: 'Capital Markets' },
  'RBLX': { sector: 'Communication Services', industry: 'Electronic Gaming & Multimedia' },
  'U': { sector: 'Technology', industry: 'Software - Application' },
  'DELL': { sector: 'Technology', industry: 'Computer Hardware' },
  'HPQ': { sector: 'Technology', industry: 'Computer Hardware' },
  'HPE': { sector: 'Technology', industry: 'Communication Equipment' },
  'ANET': { sector: 'Technology', industry: 'Communication Equipment' },
  'MSI': { sector: 'Technology', industry: 'Communication Equipment' },
  'KEYS': { sector: 'Technology', industry: 'Scientific & Technical Instruments' },
  'ZBRA': { sector: 'Technology', industry: 'Computer Hardware' },
  'CTSH': { sector: 'Technology', industry: 'Information Technology Services' },
  'EPAM': { sector: 'Technology', industry: 'Information Technology Services' },
  'IT': { sector: 'Technology', industry: 'Information Technology Services' },

  // ===== HEALTHCARE =====
  'UNH': { sector: 'Healthcare', industry: 'Healthcare Plans' },
  'JNJ': { sector: 'Healthcare', industry: 'Drug Manufacturers - General' },
  'LLY': { sector: 'Healthcare', industry: 'Drug Manufacturers - General' },
  'PFE': { sector: 'Healthcare', industry: 'Drug Manufacturers - General' },
  'MRK': { sector: 'Healthcare', industry: 'Drug Manufacturers - General' },
  'ABBV': { sector: 'Healthcare', industry: 'Drug Manufacturers - General' },
  'TMO': { sector: 'Healthcare', industry: 'Diagnostics & Research' },
  'ABT': { sector: 'Healthcare', industry: 'Medical Devices' },
  'DHR': { sector: 'Healthcare', industry: 'Diagnostics & Research' },
  'BMY': { sector: 'Healthcare', industry: 'Drug Manufacturers - General' },
  'AMGN': { sector: 'Healthcare', industry: 'Drug Manufacturers - General' },
  'GILD': { sector: 'Healthcare', industry: 'Drug Manufacturers - General' },
  'ISRG': { sector: 'Healthcare', industry: 'Medical Instruments & Supplies' },
  'VRTX': { sector: 'Healthcare', industry: 'Biotechnology' },
  'REGN': { sector: 'Healthcare', industry: 'Biotechnology' },
  'MDT': { sector: 'Healthcare', industry: 'Medical Devices' },
  'SYK': { sector: 'Healthcare', industry: 'Medical Devices' },
  'BDX': { sector: 'Healthcare', industry: 'Medical Instruments & Supplies' },
  'ZTS': { sector: 'Healthcare', industry: 'Drug Manufacturers - Specialty & Generic' },
  'BSX': { sector: 'Healthcare', industry: 'Medical Devices' },
  'EW': { sector: 'Healthcare', industry: 'Medical Devices' },
  'CI': { sector: 'Healthcare', industry: 'Healthcare Plans' },
  'HCA': { sector: 'Healthcare', industry: 'Medical Care Facilities' },
  'CVS': { sector: 'Healthcare', industry: 'Healthcare Plans' },
  'MCK': { sector: 'Healthcare', industry: 'Medical Distribution' },
  'HUM': { sector: 'Healthcare', industry: 'Healthcare Plans' },
  'CNC': { sector: 'Healthcare', industry: 'Healthcare Plans' },
  'MOH': { sector: 'Healthcare', industry: 'Healthcare Plans' },
  'A': { sector: 'Healthcare', industry: 'Diagnostics & Research' },
  'IQV': { sector: 'Healthcare', industry: 'Diagnostics & Research' },
  'DXCM': { sector: 'Healthcare', industry: 'Medical Devices' },
  'IDXX': { sector: 'Healthcare', industry: 'Diagnostics & Research' },
  'BIIB': { sector: 'Healthcare', industry: 'Drug Manufacturers - General' },
  'MRNA': { sector: 'Healthcare', industry: 'Biotechnology' },
  'ALGN': { sector: 'Healthcare', industry: 'Medical Devices' },
  'HOLX': { sector: 'Healthcare', industry: 'Medical Instruments & Supplies' },
  'BAX': { sector: 'Healthcare', industry: 'Medical Instruments & Supplies' },
  'RMD': { sector: 'Healthcare', industry: 'Medical Devices' },
  'WST': { sector: 'Healthcare', industry: 'Medical Instruments & Supplies' },
  'PODD': { sector: 'Healthcare', industry: 'Medical Devices' },

  // ===== FINANCIAL SERVICES =====
  'BRK-B': { sector: 'Financial Services', industry: 'Insurance - Diversified' },
  'JPM': { sector: 'Financial Services', industry: 'Banks - Diversified' },
  'V': { sector: 'Financial Services', industry: 'Credit Services' },
  'MA': { sector: 'Financial Services', industry: 'Credit Services' },
  'BAC': { sector: 'Financial Services', industry: 'Banks - Diversified' },
  'WFC': { sector: 'Financial Services', industry: 'Banks - Diversified' },
  'GS': { sector: 'Financial Services', industry: 'Capital Markets' },
  'MS': { sector: 'Financial Services', industry: 'Capital Markets' },
  'SCHW': { sector: 'Financial Services', industry: 'Capital Markets' },
  'AXP': { sector: 'Financial Services', industry: 'Credit Services' },
  'BLK': { sector: 'Financial Services', industry: 'Asset Management' },
  'C': { sector: 'Financial Services', industry: 'Banks - Diversified' },
  'SPGI': { sector: 'Financial Services', industry: 'Financial Data & Stock Exchanges' },
  'ICE': { sector: 'Financial Services', industry: 'Financial Data & Stock Exchanges' },
  'CME': { sector: 'Financial Services', industry: 'Financial Data & Stock Exchanges' },
  'AON': { sector: 'Financial Services', industry: 'Insurance - Brokers' },
  'MMC': { sector: 'Financial Services', industry: 'Insurance - Brokers' },
  'PGR': { sector: 'Financial Services', industry: 'Insurance - Property & Casualty' },
  'CB': { sector: 'Financial Services', industry: 'Insurance - Property & Casualty' },
  'MET': { sector: 'Financial Services', industry: 'Insurance - Life' },
  'AIG': { sector: 'Financial Services', industry: 'Insurance - Diversified' },
  'TRV': { sector: 'Financial Services', industry: 'Insurance - Property & Casualty' },
  'ALL': { sector: 'Financial Services', industry: 'Insurance - Property & Casualty' },
  'AJG': { sector: 'Financial Services', industry: 'Insurance - Brokers' },
  'AFL': { sector: 'Financial Services', industry: 'Insurance - Life' },
  'PRU': { sector: 'Financial Services', industry: 'Insurance - Life' },
  'FIS': { sector: 'Technology', industry: 'Information Technology Services' },
  'FISV': { sector: 'Technology', industry: 'Information Technology Services' },
  'GPN': { sector: 'Technology', industry: 'Information Technology Services' },
  'COF': { sector: 'Financial Services', industry: 'Credit Services' },
  'USB': { sector: 'Financial Services', industry: 'Banks - Regional' },
  'PNC': { sector: 'Financial Services', industry: 'Banks - Regional' },
  'TFC': { sector: 'Financial Services', industry: 'Banks - Regional' },
  'BK': { sector: 'Financial Services', industry: 'Asset Management' },
  'STT': { sector: 'Financial Services', industry: 'Asset Management' },
  'NTRS': { sector: 'Financial Services', industry: 'Asset Management' },
  'DFS': { sector: 'Financial Services', industry: 'Credit Services' },
  'SYF': { sector: 'Financial Services', industry: 'Credit Services' },
  'CFG': { sector: 'Financial Services', industry: 'Banks - Regional' },
  'FITB': { sector: 'Financial Services', industry: 'Banks - Regional' },

  // ===== CONSUMER CYCLICAL =====
  'HD': { sector: 'Consumer Cyclical', industry: 'Home Improvement Retail' },
  'LOW': { sector: 'Consumer Cyclical', industry: 'Home Improvement Retail' },
  'NKE': { sector: 'Consumer Cyclical', industry: 'Footwear & Accessories' },
  'SBUX': { sector: 'Consumer Cyclical', industry: 'Restaurants' },
  'MCD': { sector: 'Consumer Cyclical', industry: 'Restaurants' },
  'TJX': { sector: 'Consumer Cyclical', industry: 'Apparel Retail' },
  'ROST': { sector: 'Consumer Cyclical', industry: 'Apparel Retail' },
  'ORLY': { sector: 'Consumer Cyclical', industry: 'Specialty Retail' },
  'AZO': { sector: 'Consumer Cyclical', industry: 'Specialty Retail' },
  'BKNG': { sector: 'Consumer Cyclical', industry: 'Travel Services' },
  'MAR': { sector: 'Consumer Cyclical', industry: 'Lodging' },
  'HLT': { sector: 'Consumer Cyclical', industry: 'Lodging' },
  'RCL': { sector: 'Consumer Cyclical', industry: 'Travel Services' },
  'CCL': { sector: 'Consumer Cyclical', industry: 'Travel Services' },
  'GM': { sector: 'Consumer Cyclical', industry: 'Auto Manufacturers' },
  'F': { sector: 'Consumer Cyclical', industry: 'Auto Manufacturers' },
  'TM': { sector: 'Consumer Cyclical', industry: 'Auto Manufacturers' },
  'RACE': { sector: 'Consumer Cyclical', industry: 'Auto Manufacturers' },
  'CMG': { sector: 'Consumer Cyclical', industry: 'Restaurants' },
  'YUM': { sector: 'Consumer Cyclical', industry: 'Restaurants' },
  'DPZ': { sector: 'Consumer Cyclical', industry: 'Restaurants' },
  'DHI': { sector: 'Consumer Cyclical', industry: 'Residential Construction' },
  'LEN': { sector: 'Consumer Cyclical', industry: 'Residential Construction' },
  'PHM': { sector: 'Consumer Cyclical', industry: 'Residential Construction' },
  'NVR': { sector: 'Consumer Cyclical', industry: 'Residential Construction' },
  'GRMN': { sector: 'Technology', industry: 'Scientific & Technical Instruments' },
  'POOL': { sector: 'Consumer Cyclical', industry: 'Leisure' },
  'BBY': { sector: 'Consumer Cyclical', industry: 'Specialty Retail' },
  'TSCO': { sector: 'Consumer Cyclical', industry: 'Specialty Retail' },
  'DG': { sector: 'Consumer Defensive', industry: 'Discount Stores' },
  'DLTR': { sector: 'Consumer Defensive', industry: 'Discount Stores' },
  'EBAY': { sector: 'Consumer Cyclical', industry: 'Internet Retail' },
  'ETSY': { sector: 'Consumer Cyclical', industry: 'Internet Retail' },
  'W': { sector: 'Consumer Cyclical', industry: 'Internet Retail' },
  'LULU': { sector: 'Consumer Cyclical', industry: 'Apparel Retail' },
  'GPS': { sector: 'Consumer Cyclical', industry: 'Apparel Retail' },
  'TPR': { sector: 'Consumer Cyclical', industry: 'Luxury Goods' },
  'RL': { sector: 'Consumer Cyclical', industry: 'Apparel Manufacturing' },
  'DECK': { sector: 'Consumer Cyclical', industry: 'Footwear & Accessories' },
  'BIRK': { sector: 'Consumer Cyclical', industry: 'Footwear & Accessories' },

  // ===== CONSUMER DEFENSIVE =====
  'WMT': { sector: 'Consumer Defensive', industry: 'Discount Stores' },
  'PG': { sector: 'Consumer Defensive', industry: 'Household & Personal Products' },
  'KO': { sector: 'Consumer Defensive', industry: 'Beverages - Non-Alcoholic' },
  'PEP': { sector: 'Consumer Defensive', industry: 'Beverages - Non-Alcoholic' },
  'COST': { sector: 'Consumer Defensive', industry: 'Discount Stores' },
  'PM': { sector: 'Consumer Defensive', industry: 'Tobacco' },
  'MO': { sector: 'Consumer Defensive', industry: 'Tobacco' },
  'CL': { sector: 'Consumer Defensive', industry: 'Household & Personal Products' },
  'MDLZ': { sector: 'Consumer Defensive', industry: 'Confectioners' },
  'GIS': { sector: 'Consumer Defensive', industry: 'Packaged Foods' },
  'KHC': { sector: 'Consumer Defensive', industry: 'Packaged Foods' },
  'SYY': { sector: 'Consumer Defensive', industry: 'Food Distribution' },
  'HSY': { sector: 'Consumer Defensive', industry: 'Confectioners' },
  'K': { sector: 'Consumer Defensive', industry: 'Packaged Foods' },
  'KMB': { sector: 'Consumer Defensive', industry: 'Household & Personal Products' },
  'CAG': { sector: 'Consumer Defensive', industry: 'Packaged Foods' },
  'CPB': { sector: 'Consumer Defensive', industry: 'Packaged Foods' },
  'SJM': { sector: 'Consumer Defensive', industry: 'Packaged Foods' },
  'HRL': { sector: 'Consumer Defensive', industry: 'Packaged Foods' },
  'TSN': { sector: 'Consumer Defensive', industry: 'Farm Products' },
  'ADM': { sector: 'Consumer Defensive', industry: 'Farm Products' },
  'BG': { sector: 'Consumer Defensive', industry: 'Farm Products' },
  'STZ': { sector: 'Consumer Defensive', industry: 'Beverages - Wineries & Distilleries' },
  'TAP': { sector: 'Consumer Defensive', industry: 'Beverages - Brewers' },
  'SAM': { sector: 'Consumer Defensive', industry: 'Beverages - Brewers' },
  'KDP': { sector: 'Consumer Defensive', industry: 'Beverages - Non-Alcoholic' },
  'MNST': { sector: 'Consumer Defensive', industry: 'Beverages - Non-Alcoholic' },
  'EL': { sector: 'Consumer Defensive', industry: 'Household & Personal Products' },
  'CHD': { sector: 'Consumer Defensive', industry: 'Household & Personal Products' },
  'CLX': { sector: 'Consumer Defensive', industry: 'Household & Personal Products' },

  // ===== INDUSTRIALS =====
  'CAT': { sector: 'Industrials', industry: 'Farm & Heavy Construction Machinery' },
  'DE': { sector: 'Industrials', industry: 'Farm & Heavy Construction Machinery' },
  'HON': { sector: 'Industrials', industry: 'Conglomerates' },
  'UPS': { sector: 'Industrials', industry: 'Integrated Freight & Logistics' },
  'BA': { sector: 'Industrials', industry: 'Aerospace & Defense' },
  'GE': { sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  'RTX': { sector: 'Industrials', industry: 'Aerospace & Defense' },
  'LMT': { sector: 'Industrials', industry: 'Aerospace & Defense' },
  'GD': { sector: 'Industrials', industry: 'Aerospace & Defense' },
  'NOC': { sector: 'Industrials', industry: 'Aerospace & Defense' },
  'MMM': { sector: 'Industrials', industry: 'Conglomerates' },
  'EMR': { sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  'ROK': { sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  'ETN': { sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  'ITW': { sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  'PH': { sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  'IR': { sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  'CMI': { sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  'PCAR': { sector: 'Industrials', industry: 'Farm & Heavy Construction Machinery' },
  'OTIS': { sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  'CARR': { sector: 'Industrials', industry: 'Building Products & Equipment' },
  'JCI': { sector: 'Industrials', industry: 'Building Products & Equipment' },
  'SWK': { sector: 'Industrials', industry: 'Tools & Accessories' },
  'FDX': { sector: 'Industrials', industry: 'Integrated Freight & Logistics' },
  'CSX': { sector: 'Industrials', industry: 'Railroads' },
  'UNP': { sector: 'Industrials', industry: 'Railroads' },
  'NSC': { sector: 'Industrials', industry: 'Railroads' },
  'DAL': { sector: 'Industrials', industry: 'Airlines' },
  'UAL': { sector: 'Industrials', industry: 'Airlines' },
  'LUV': { sector: 'Industrials', industry: 'Airlines' },
  'WM': { sector: 'Industrials', industry: 'Waste Management' },
  'RSG': { sector: 'Industrials', industry: 'Waste Management' },
  'VRSK': { sector: 'Industrials', industry: 'Consulting Services' },
  'PAYX': { sector: 'Industrials', industry: 'Staffing & Employment Services' },
  'ADP': { sector: 'Industrials', industry: 'Staffing & Employment Services' },
  'CTAS': { sector: 'Industrials', industry: 'Specialty Business Services' },
  'FAST': { sector: 'Industrials', industry: 'Industrial Distribution' },
  'GWW': { sector: 'Industrials', industry: 'Industrial Distribution' },
  'URI': { sector: 'Industrials', industry: 'Rental & Leasing Services' },
  'PWR': { sector: 'Industrials', industry: 'Engineering & Construction' },

  // ===== ENERGY =====
  'XOM': { sector: 'Energy', industry: 'Oil & Gas Integrated' },
  'CVX': { sector: 'Energy', industry: 'Oil & Gas Integrated' },
  'COP': { sector: 'Energy', industry: 'Oil & Gas E&P' },
  'SLB': { sector: 'Energy', industry: 'Oil & Gas Equipment & Services' },
  'EOG': { sector: 'Energy', industry: 'Oil & Gas E&P' },
  'MPC': { sector: 'Energy', industry: 'Oil & Gas Refining & Marketing' },
  'VLO': { sector: 'Energy', industry: 'Oil & Gas Refining & Marketing' },
  'PSX': { sector: 'Energy', industry: 'Oil & Gas Refining & Marketing' },
  'PXD': { sector: 'Energy', industry: 'Oil & Gas E&P' },
  'OXY': { sector: 'Energy', industry: 'Oil & Gas E&P' },
  'WMB': { sector: 'Energy', industry: 'Oil & Gas Midstream' },
  'KMI': { sector: 'Energy', industry: 'Oil & Gas Midstream' },
  'HAL': { sector: 'Energy', industry: 'Oil & Gas Equipment & Services' },
  'DVN': { sector: 'Energy', industry: 'Oil & Gas E&P' },
  'FANG': { sector: 'Energy', industry: 'Oil & Gas E&P' },
  'HES': { sector: 'Energy', industry: 'Oil & Gas E&P' },
  'BKR': { sector: 'Energy', industry: 'Oil & Gas Equipment & Services' },
  'TRGP': { sector: 'Energy', industry: 'Oil & Gas Midstream' },
  'OKE': { sector: 'Energy', industry: 'Oil & Gas Midstream' },
  'CTRA': { sector: 'Energy', industry: 'Oil & Gas E&P' },

  // ===== COMMUNICATION SERVICES =====
  'DIS': { sector: 'Communication Services', industry: 'Entertainment' },
  'CMCSA': { sector: 'Communication Services', industry: 'Entertainment' },
  'T': { sector: 'Communication Services', industry: 'Telecom Services' },
  'TMUS': { sector: 'Communication Services', industry: 'Telecom Services' },
  'VZ': { sector: 'Communication Services', industry: 'Telecom Services' },
  'CHTR': { sector: 'Communication Services', industry: 'Entertainment' },
  'EA': { sector: 'Communication Services', industry: 'Electronic Gaming & Multimedia' },
  'TTWO': { sector: 'Communication Services', industry: 'Electronic Gaming & Multimedia' },
  'MTCH': { sector: 'Communication Services', industry: 'Internet Content & Information' },
  'LYV': { sector: 'Communication Services', industry: 'Entertainment' },
  'NWSA': { sector: 'Communication Services', industry: 'Publishing' },
  'OMC': { sector: 'Communication Services', industry: 'Advertising Agencies' },
  'IPG': { sector: 'Communication Services', industry: 'Advertising Agencies' },
  'FOXA': { sector: 'Communication Services', industry: 'Entertainment' },
  'PARA': { sector: 'Communication Services', industry: 'Entertainment' },
  'WBD': { sector: 'Communication Services', industry: 'Entertainment' },
  'ROKU': { sector: 'Communication Services', industry: 'Entertainment' },
  'SPOT': { sector: 'Communication Services', industry: 'Internet Content & Information' },
  'PINS': { sector: 'Communication Services', industry: 'Internet Content & Information' },
  'SNAP': { sector: 'Communication Services', industry: 'Internet Content & Information' },

  // ===== UTILITIES =====
  'NEE': { sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  'DUK': { sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  'SO': { sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  'D': { sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  'AEP': { sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  'SRE': { sector: 'Utilities', industry: 'Utilities - Diversified' },
  'EXC': { sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  'XEL': { sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  'ED': { sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  'WEC': { sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  'ES': { sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  'AEE': { sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  'DTE': { sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  'PEG': { sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  'CMS': { sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  'FE': { sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  'AWK': { sector: 'Utilities', industry: 'Utilities - Regulated Water' },
  'EVRG': { sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  'ATO': { sector: 'Utilities', industry: 'Utilities - Regulated Gas' },
  'NI': { sector: 'Utilities', industry: 'Utilities - Regulated Gas' },

  // ===== REAL ESTATE =====
  'PLD': { sector: 'Real Estate', industry: 'REIT - Industrial' },
  'AMT': { sector: 'Real Estate', industry: 'REIT - Specialty' },
  'CCI': { sector: 'Real Estate', industry: 'REIT - Specialty' },
  'EQIX': { sector: 'Real Estate', industry: 'REIT - Specialty' },
  'PSA': { sector: 'Real Estate', industry: 'REIT - Industrial' },
  'SPG': { sector: 'Real Estate', industry: 'REIT - Retail' },
  'O': { sector: 'Real Estate', industry: 'REIT - Retail' },
  'WELL': { sector: 'Real Estate', industry: 'REIT - Healthcare Facilities' },
  'DLR': { sector: 'Real Estate', industry: 'REIT - Specialty' },
  'AVB': { sector: 'Real Estate', industry: 'REIT - Residential' },
  'EQR': { sector: 'Real Estate', industry: 'REIT - Residential' },
  'VTR': { sector: 'Real Estate', industry: 'REIT - Healthcare Facilities' },
  'ARE': { sector: 'Real Estate', industry: 'REIT - Office' },
  'MAA': { sector: 'Real Estate', industry: 'REIT - Residential' },
  'UDR': { sector: 'Real Estate', industry: 'REIT - Residential' },
  'ESS': { sector: 'Real Estate', industry: 'REIT - Residential' },
  'PEAK': { sector: 'Real Estate', industry: 'REIT - Healthcare Facilities' },
  'HST': { sector: 'Real Estate', industry: 'REIT - Hotel & Motel' },
  'KIM': { sector: 'Real Estate', industry: 'REIT - Retail' },
  'REG': { sector: 'Real Estate', industry: 'REIT - Retail' },

  // ===== BASIC MATERIALS =====
  'LIN': { sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  'APD': { sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  'SHW': { sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  'ECL': { sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  'NEM': { sector: 'Basic Materials', industry: 'Gold' },
  'FCX': { sector: 'Basic Materials', industry: 'Copper' },
  'NUE': { sector: 'Basic Materials', industry: 'Steel' },
  'DOW': { sector: 'Basic Materials', industry: 'Chemicals' },
  'DD': { sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  'PPG': { sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  'VMC': { sector: 'Basic Materials', industry: 'Building Materials' },
  'MLM': { sector: 'Basic Materials', industry: 'Building Materials' },
  'ALB': { sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  'FMC': { sector: 'Basic Materials', industry: 'Agricultural Inputs' },
  'CE': { sector: 'Basic Materials', industry: 'Chemicals' },
  'CF': { sector: 'Basic Materials', industry: 'Agricultural Inputs' },
  'MOS': { sector: 'Basic Materials', industry: 'Agricultural Inputs' },
  'CTVA': { sector: 'Basic Materials', industry: 'Agricultural Inputs' },
  'IFF': { sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  'EMN': { sector: 'Basic Materials', industry: 'Specialty Chemicals' },

  // ===== INDIAN MARKET (NIFTY 50) =====
  'RELIANCE.NS': { sector: 'Energy', industry: 'Oil & Gas Refining & Marketing' },
  'TCS.NS': { sector: 'Technology', industry: 'Information Technology Services' },
  'HDFCBANK.NS': { sector: 'Financial Services', industry: 'Banks - Regional' },
  'INFY.NS': { sector: 'Technology', industry: 'Information Technology Services' },
  'ICICIBANK.NS': { sector: 'Financial Services', industry: 'Banks - Regional' },
  'HINDUNILVR.NS': { sector: 'Consumer Defensive', industry: 'Household & Personal Products' },
  'SBIN.NS': { sector: 'Financial Services', industry: 'Banks - Regional' },
  'BHARTIARTL.NS': { sector: 'Communication Services', industry: 'Telecom Services' },
  'ITC.NS': { sector: 'Consumer Defensive', industry: 'Tobacco' },
  'KOTAKBANK.NS': { sector: 'Financial Services', industry: 'Banks - Regional' },
  'LT.NS': { sector: 'Industrials', industry: 'Engineering & Construction' },
  'AXISBANK.NS': { sector: 'Financial Services', industry: 'Banks - Regional' },
  'BAJFINANCE.NS': { sector: 'Financial Services', industry: 'Financial Conglomerates' },
  'ASIANPAINT.NS': { sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  'MARUTI.NS': { sector: 'Consumer Cyclical', industry: 'Auto Manufacturers' },
  'HCLTECH.NS': { sector: 'Technology', industry: 'Information Technology Services' },
  'TITAN.NS': { sector: 'Consumer Cyclical', industry: 'Luxury Goods' },
  'SUNPHARMA.NS': { sector: 'Healthcare', industry: 'Drug Manufacturers - Specialty & Generic' },
  'WIPRO.NS': { sector: 'Technology', industry: 'Information Technology Services' },
  'ULTRACEMCO.NS': { sector: 'Basic Materials', industry: 'Building Materials' },
  'NTPC.NS': { sector: 'Utilities', industry: 'Utilities - Independent Power Producers' },
  'NESTLEIND.NS': { sector: 'Consumer Defensive', industry: 'Packaged Foods' },
  'POWERGRID.NS': { sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  'TATAMOTORS.NS': { sector: 'Consumer Cyclical', industry: 'Auto Manufacturers' },
  'M&M.NS': { sector: 'Consumer Cyclical', industry: 'Auto Manufacturers' },
  'JSWSTEEL.NS': { sector: 'Basic Materials', industry: 'Steel' },
  'TATASTEEL.NS': { sector: 'Basic Materials', industry: 'Steel' },
  'ADANIPORTS.NS': { sector: 'Industrials', industry: 'Marine Shipping' },
  'BAJAJFINSV.NS': { sector: 'Financial Services', industry: 'Financial Conglomerates' },
  'TECHM.NS': { sector: 'Technology', industry: 'Information Technology Services' },
  'ONGC.NS': { sector: 'Energy', industry: 'Oil & Gas E&P' },
  'HDFCLIFE.NS': { sector: 'Financial Services', industry: 'Insurance - Life' },
  'DIVISLAB.NS': { sector: 'Healthcare', industry: 'Drug Manufacturers - Specialty & Generic' },
  'COALINDIA.NS': { sector: 'Energy', industry: 'Thermal Coal' },
  'GRASIM.NS': { sector: 'Basic Materials', industry: 'Building Materials' },
  'BRITANNIA.NS': { sector: 'Consumer Defensive', industry: 'Packaged Foods' },
  'BPCL.NS': { sector: 'Energy', industry: 'Oil & Gas Refining & Marketing' },
  'DRREDDY.NS': { sector: 'Healthcare', industry: 'Drug Manufacturers - Specialty & Generic' },
  'CIPLA.NS': { sector: 'Healthcare', industry: 'Drug Manufacturers - Specialty & Generic' },
  'APOLLOHOSP.NS': { sector: 'Healthcare', industry: 'Medical Care Facilities' },
  'EICHERMOT.NS': { sector: 'Consumer Cyclical', industry: 'Auto Manufacturers' },
  'INDUSINDBK.NS': { sector: 'Financial Services', industry: 'Banks - Regional' },
  'SBILIFE.NS': { sector: 'Financial Services', industry: 'Insurance - Life' },
  'TATACONSUM.NS': { sector: 'Consumer Defensive', industry: 'Packaged Foods' },
  'HEROMOTOCO.NS': { sector: 'Consumer Cyclical', industry: 'Auto Manufacturers' },
};

/**
 * Get sector/industry for a symbol from the static map.
 * Returns undefined if not found.
 */
export function getStaticSectorInfo(symbol: string): SectorInfo | undefined {
  return STOCK_SECTORS[symbol];
}
